# Generated by Django 4.2.4 on 2024-02-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subheader', models.CharField(blank=True, max_length=200)),
                ('progress', models.IntegerField()),
                ('end_date', models.DateField()),
                ('participants', models.ManyToManyField(related_name='projects', to='core.participant')),
            ],
        ),
    ]
