# Generated by Django 4.2.4 on 2024-02-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=50)),
                ('current_price', models.FloatField()),
                ('open_price', models.FloatField()),
                ('percentage_change', models.FloatField()),
                ('info', models.JSONField(blank=True, null=True)),
                ('date_fetched', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
