# Generated by Django 4.2.10 on 2024-02-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_stockdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='sector',
        ),
    ]
