# Generated by Django 4.2.10 on 2024-02-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_stockdata_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
